version: '3.8'

services:
  #mysql:
    #image: mysql:8.0
    #container_name: mysql_db_bolechas
    #restart: always
    #environment:
    #  MYSQL_ROOT_PASSWORD: root
    #ports:
    #  - "3306:3306"
    #volumes:
    #  - mysql_data:/var/lib/mysql
    #  - ./initMysql.sql:/docker-entrypoint-initdb.d/initMysql.sql
    #command: --default-authentication-plugin=mysql_native_password

  mariadb:
    image: mariadb:10.11
    container_name: bolechasMaria
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
      MARIADB_USER: usuario
      MARIADB_PASSWORD: usuario123
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./initMariaDB.sql:/docker-entrypoint-initdb.d/initMariaDB.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"

volumes:
  mariadb_data:
